### PR TITLE
(GH-226) Respond quickly to VMs being consumed

### PR DESCRIPTION
**Pull request by glennsarti**
Previously in commit 9b0e55f the looping period was changed from a static
number to a dynamic one depending on load, however this meant that the operation
to refill a pool was slowed down somewhat.  While not a problem under normal
loads, when a pool was quickly consumed, the pool manager may not respond
quickly enough to refill the pool.  This commit:

- Changes the sleep method, to us a helper sleep method that will wakeup
  periodically and evaluate other wakeup events.  This could be used later to
  exit sleep loops when pooler is shutting down to stop blocking threads
- By default the wakeup_period is set to the minimum pool check loop time, thus
  emulating the behaviour prior to commit 9b0e55f
- Adds tests for the behaviour

### CODE REVIEW

**Comment by shrug** [comment]
@mattkirby ping, when you get a sec

**Comment by shrug** [comment]
```
Gem::InstallError: redis requires Ruby version >= 2.2.2.
```
Do we need to pin the version of the redis gem?

**Comment by glennsarti** [comment]
Doh...looks like we do :-(

I'll add this to the this PR

**Comment by glennsarti** [comment]
@shrug Done.  Nokogiri needed some work too.

**Comment by glennsarti** [comment]
Thanks @mattkirby

**Pull request merged**
