### PR TITLE
Add basic auth token functionality

### PR DESCRIPTION
**Pull request by sschneid**
...and rspec tests, hooray!

### CODE REVIEW

**Comment by sschneid** [comment]
Deployed in dev, usage example here: https://gist.github.com/sschneid/419a20ac35c154d9a4d6

**Comment by colinPL** [comment]
:+1:

**Comment by rji** [comment]
Could we update the docs and example config with this new functionality before merge?

**Comment by sschneid** [comment]
@rji Yup, forthcoming.  I'll tag this as 'blocked' until I add an additional commit with these things.

**Comment by rji** [comment]
Awesome, thanks! Otherwise the patch looks good to me.

**Comment by sschneid** [comment]
Docs updated.

**Comment by rji** [comment]
:+1:

**Pull request merged**
