### PR TITLE
(QENG-2056) Create daily tag indexes, report in /summary

### PR DESCRIPTION
**Pull request by sschneid**
- Store daily tag roll-ups in vmpooler__tag__<date>
- GET /summary will display daily tag counts and roll-up

### CODE REVIEW

**Comment by colinPL** [comment]
Can you add a spec test?

**Comment by sschneid** [comment]
> Can you add a spec test?

Yup... in-progress.  I'll mark this as "blocked" until.

**Comment by sschneid** [comment]
Spec for `get_tag_metrics` method added.

**Comment by rji** [comment]
Looks good to me. :+1:

**Pull request merged**
