### PR TITLE
Update usage of global variablesin vsphere_helper

### PR DESCRIPTION
**Pull request by mattkirby**
This commit updates usage of global variables in vsphere_helper to be instance variables. They do not need to be global variables as brought up in issue #194. Without this change we are setting global variables when they are not needed.

### CODE REVIEW

**Comment by mattkirby** [comment]
Would it be better to submit this as a PR to #196 so there's a place for them?

**Comment by glennsarti** [comment]
Um.. Not sure.  My intent in 196 was to document the existing behaviour only and then we can submit later PRs to modify the behaviour.  However I'm not averse to this PR being merged prior to 196.  All it's doing is just shifting when the work gets done :-)

**Comment by shrug** [comment]
I think this needs a rebase

**Comment by glennsarti** [comment]
@shrug Rebased on @mattkirby 's behalf

**Pull request merged**
