### PR TITLE
Updated Vagrant box and associated docs

### PR DESCRIPTION
**Pull request by genebean**
This move vmpooler to my newer Vagrant box and also documents how to run directly in Vagrant using different versions of ruby.

### CODE REVIEW

**Comment by shrug** [comment]
It looks like we need to pin to an older redis gem for tests...

**Comment by glennsarti** [comment]
Needs a rebase

**Comment by shrug** [comment]
@genebean Can you rebase?

**Comment by genebean** [comment]
@shrug Rebased.

**Pull request merged**
