### PR TITLE
(POOLER-70)(POOLER-52) Create a functional vSphere Provider 

### PR DESCRIPTION
**Pull request by glennsarti**
Todo

- [x] Copy vsphere helper code into the provider
- [x] Get initial set of tests working
- [x] Modify the provider to make it easier to add a connection pooler later
- [x] Need to add snapshot and add disk abstractions into base class
- [x] Try this against a real vSphere instance

Populate the functions

- [x] name
- [x] vms_in_pool
- [x] get_vm_host
- [x] find_least_used_compatible_host
- [x] migrate_vm_to_host
- [x] get_vm
- [x] create_vm
- [x] destroy_vm
- [x] vm_ready?
- [x] vm_exists?
- [x] create_disk
- [x] create_snapshot
- [x] revert_snapshot
- [x] Move provider helpers into base class + tests

### CODE REVIEW

**Comment by glennsarti** [comment]
I have tested each of the new functions in the vSphere provider on a real vSphere instance and so far behave as expected.  This combined with the large unit test suite gives me confidence that these changes are not breaking.

Note that this new code is still not yet executed by the Pool Manager.  That will be coming in the next PR.  This is to get the provider code in for review and testing.

**Comment by mattkirby** [comment]
This looks reasonable to me, I've given my +1. Do you expect the build to succeed? I'd like to  determine whether this should wait for successful Travis CI build.

**Comment by glennsarti** [comment]
Odd...travis should be green...will go back and repush

**Comment by glennsarti** [comment]
@mattkirby I broke one of my tests.  Fixed up and running through Travis now.

**Comment by mattkirby** [comment]
Thanks, looks good now!

**Pull request merged**
